In [6]:
import numpy as np

# ---------- Given data ----------
mu = np.array([0.08, 0.12, 0.16])        # Expected returns
sigma = np.array([0.25, 0.25, 0.30])     # Standard deviations
rf = 0.04                                # Risk-free rate

# Correlation matrix
rho = np.array([
    [1.00, -0.25,  0.25],
    [-0.25, 1.00, -0.25],
    [0.25, -0.25,  1.00]
])

# Covariance matrix
Sigma = np.outer(sigma, sigma) * rho

# ---------- (i) Tangency Portfolio ----------
# Compute excess returns (over the risk-free rate)
excess_mu = mu - rf

# Inverse of the covariance matrix
Sigma_inv = np.linalg.inv(Sigma)

# Tangency portfolio weights (only risky assets, sum to 1)
w_tangency = Sigma_inv @ excess_mu
w_tangency /= np.sum(w_tangency)

# Expected return and standard deviation
mu_tangency = w_tangency @ mu
sigma_tangency = np.sqrt(w_tangency @ Sigma @ w_tangency)
sharpe_tangency = (mu_tangency - rf) / sigma_tangency

print("=== Tangency Portfolio ===")
print("Weights:", w_tangency)
print("Expected return: {:.4f}".format(mu_tangency))
print("Standard deviation: {:.4f}".format(sigma_tangency))
print("Sharpe ratio: {:.4f}".format(sharpe_tangency))



=== Tangency Portfolio ===
Weights: [0.15384615 0.46153846 0.38461538]
Expected return: 0.1292
Standard deviation: 0.1465
Sharpe ratio: 0.6093


In [9]:
Sigma

array([[ 0.0625  , -0.015625,  0.01875 ],
       [-0.015625,  0.0625  , -0.01875 ],
       [ 0.01875 , -0.01875 ,  0.09    ]])

In [8]:
Sigma_inv

array([[17.77777778,  3.55555556, -2.96296296],
       [ 3.55555556, 17.77777778,  2.96296296],
       [-2.96296296,  2.96296296, 12.34567901]])

In [10]:
excess_mu

array([0.04, 0.08, 0.12])

In [11]:
w_tangency

array([0.15384615, 0.46153846, 0.38461538])