In [5]:
import numpy as np

# ---------- Given data ----------
mu = np.array([0.08, 0.12, 0.16])        # Expected returns
sigma = np.array([0.25, 0.25, 0.30])     # Standard deviations
rf = 0.04                                # Risk-free rate

# Correlation matrix
rho = np.array([
    [1.00, -0.25,  0.25],
    [-0.25, 1.00, -0.25],
    [0.25, -0.25,  1.00]
])
# Covariance matrix
Sigma = np.outer(sigma, sigma) * rho

# excess return
excess_mu = mu - rf

# Inverse of the covariance matrix
Sigma_inv = np.linalg.inv(Sigma)


# ---------- Minimum Variance Portfolio ----------
ones = np.ones(len(mu))
w_mvp = Sigma_inv @ ones
w_mvp /= np.sum(w_mvp)

mu_mvp = w_mvp @ mu
sigma_mvp = np.sqrt(w_mvp @ Sigma @ w_mvp)

print("\n=== Minimum Variance Portfolio ===")
print("Weights:", w_mvp)
print("Expected return: {:.4f}".format(mu_mvp))
print("Standard deviation: {:.4f}".format(sigma_mvp))



=== Minimum Variance Portfolio ===
Weights: [0.33393178 0.44165171 0.22441652]
Expected return: 0.1156
Standard deviation: 0.1348


In [6]:
Sigma

array([[ 0.0625  , -0.015625,  0.01875 ],
       [-0.015625,  0.0625  , -0.01875 ],
       [ 0.01875 , -0.01875 ,  0.09    ]])

In [7]:
excess_mu

array([0.04, 0.08, 0.12])

In [8]:
Sigma_inv

array([[17.77777778,  3.55555556, -2.96296296],
       [ 3.55555556, 17.77777778,  2.96296296],
       [-2.96296296,  2.96296296, 12.34567901]])